2021-02-09 20:44:19,463 ERROR: Exception on / [GET] [in C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kyuti\webpage\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form,
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kyuti\webpage\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\kyuti\webpage\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\kyuti\webpage\app\templates\base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\kyuti\webpage\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\kyuti\webpage\app\templates\_post.html", line 9, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
jinja2.exceptions.UndefinedError: 'irl_for' is undefined
2021-02-09 20:44:25,074 ERROR: Exception on / [GET] [in C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kyuti\webpage\app\routes.py", line 27, in index
    return render_template('index.html', title='Home Page', form=form,
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kyuti\webpage\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\kyuti\webpage\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\kyuti\webpage\app\templates\base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\kyuti\webpage\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\kyuti\webpage\app\templates\_post.html", line 9, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
jinja2.exceptions.UndefinedError: 'irl_for' is undefined
2021-02-09 20:44:39,597 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-02-09 20:47:09,444 ERROR: Exception on /user/edgar [GET] [in C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kyuti\webpage\app\routes.py", line 87, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\kyuti\anaconda3\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\kyuti\anaconda3\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kyuti\webpage\app\templates\user.html", line 43, in template
    <a href="{{ next_url pr '#' }}"> Older Posts <span aria-hidden="true">%lrarr;</span>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'pr'
2021-03-05 19:27:58,794 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:35:10,754 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:37:00,370 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:41:25,203 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:41:52,140 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:42:56,262 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-05 19:43:13,808 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
2021-03-09 19:06:57,947 INFO: Website Startup [in C:\Users\kyuti\webpage\app\__init__.py:46]
